language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
    global:
    - GH_REF: github.com/deformio/docs.git
    - EMAIL: web-chib@ya.ru
    - secure: "iXK8yq4+M/KUm3qDMfKtEg/XMjQG58eBMI3GZpVbbK09oiEgXgR3RfhMDPOxtq6wlbXf5fWDXe2QpZRBxuod65HoIuzz9v1gNLJ7hAAjBHfyRlZ368IdlORAdZA0ulvxoI68Q+UknkdpSRvYUrdtk/fJy3Ai62g4E0fTm91Ravnhn5XDZ+D7BXH8/W5YnedOC9rqCzLVGse9/EqDy/L5I/xwfZK1oOb2JBh/7tCEfJpep+xuSktlulfqu6zIqYdC9UAffB3tnD3ozNjElhDr+AzAJ4TFw+NbAZeetsz60UPrQSlTFmh1oQiArJfALU+M3Ttn4JvzEYsijzPEhpRQPGuEp2Rzqr5G8ZQoS8Or2efx6iRFo/535OzU33lKI5q8cmR0LR0MXhWb2JXrwoaTlqSLz+iHr1pEJleXUVJtJ8qw2yTL4l/FPsKMAr9P4lIHFw5J/xbrQ1AqjRbXDy2CuznjZxogcngz9jgvbftbXVtYyt+GmHndmx18eDSKjOEYZWUaKo+qe8qnNsXAose0J8yPAkdazpWdG2EnAuTN8wQSKeOq2gT0rhgSjI7B+2GDUnhdDGtP+/DGonpScC83WxlEnIapXnzpXG8D+xeyCBbMcYtYHPl/V1bOxpnZ2UmCHZ88IWjaPI8wi8eWfQBwzehYN58weRJcmV932RWsCV4="
script: invoke deploy
