site_name: Deform
theme: readthedocs
markdown_extensions:
    - markdown_include.include
    - admonition
pages:
- Home: index.md
- Quickstart: quickstart/index.md
- Projects: projects.md
- Collections: collections.md
- Documents: documents.md
- Schemas: schemas.md
- Files: files.md
- Tokens: tokens.md
- Processors: processors.md
- Embeds: embeds.md
- Hooks: hooks.md
- Errors Codes: errors.md
- CLI Reference: cli.md
- HTTP API Reference: cli.md
- Changelog: changelog.md
